# Generated by Django 5.2.6 on 2025-09-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(default='Bulto de arroz por 50kg', max_length=500),
            preserve_default=False,
        ),
    ]
